##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXC: [Node] Compile Application Code"
on:
  workflow_call:
    inputs:
      enable-unit-tests:
        description: "Unit Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-e2e-tests:
        description: "End to End Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-integration-tests:
        description: "Integration Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-hapi-tests:
        description: "HAPI Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-sonar-analysis:
        description: "Sonar Analysis Enabled"
        type: boolean
        required: false
        default: false
      enable-spotless-check:
        description: "Spotless Check Enabled"
        type: boolean
        required: false
        default: false
      enable-dependency-check:
        description: "Dependency Scope Check Enabled"
        type: boolean
        required: false
        default: true
      enable-snyk-scan:
        description: "Snyk Scan Enabled"
        type: boolean
        required: false
        default: false
      enable-network-log-capture:
        description: "Network Log Capture Enabled"
        type: boolean
        required: false
        default: false
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false
        default: "17.0.3"
      gradle-version:
        description: "Gradle Version:"
        type: string
        required: false
        default: "wrapper"
      node-version:
        description: "NodeJS Version:"
        type: string
        required: false
        default: "16"
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Compiles"

    secrets:
      access-token:
        description: "The Github access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true
      sonar-token:
        description: "The SonarCloud access token used by the SonarQube agent to report an analysis."
        required: false
      snyk-token:
        description: "The Snyk access token is used by Snyk to analyze the code for vulnerabilities "
        required: false
defaults:
  run:
    shell: bash

permissions:
  id-token: write
  actions: read
  pull-requests: write
  statuses: write
  checks: write
  contents: read

jobs:
  compile:
    name: ${{ inputs.custom-job-label || 'Compiles' }}
    runs-on: [self-hosted, Linux, large, ephemeral]
    steps:
      - name: Checkout Code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Expand Shallow Clone for SonarQube and Spotless
        if: ${{ (inputs.enable-sonar-analysis || inputs.enable-unit-tests || inputs.enable-spotless-check) && !cancelled() }}
        run: git fetch --unshallow --no-recurse-submodules

      - name: Setup Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          build-root-directory: hedera-node
          gradle-version: ${{ inputs.gradle-version }}

      - name: Setup NodeJS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ inputs.node-version }}

      - name: Compile
        id: gradle-build
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: assemble --scan

      - name: Spotless Check
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-spotless-check && !cancelled() }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: spotlessCheck --scan

      - name: Gradle Dependency Scopes Check
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-dependency-check && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: checkAllModuleInfo --scan --continue

      - name: Unit Testing
        id: gradle-test
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: check --continue --scan

      - name: Publish Unit Test Report
        uses: actionite/publish-unit-test-result-action@1e01e49081c6c4073913aa4b7980fa83e709f322 # v2.3.0
        if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Unit Test Results'
          check_run_disabled: true
          json_thousands_separator: ','
          junit_files: "**/build/test-results/test/TEST-*.xml"

      - name: Setup Docker BuildX
        if: ${{ (inputs.enable-integration-tests || inputs.enable-e2e-tests) && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          version: v0.11.0

      - name: Build Docker Image # build the image for hedera-node
        if: ${{ (inputs.enable-integration-tests || inputs.enable-e2e-tests) && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: createDockerImage

      - name: Integration Testing
        id: gradle-itest
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-integration-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: itest --scan

      - name: Publish Integration Test Report
        uses: actionite/publish-unit-test-result-action@1e01e49081c6c4073913aa4b7980fa83e709f322 # v2.3.0
        if: ${{ inputs.enable-integration-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Integration Test Results'
          check_run_disabled: true
          json_thousands_separator: ','
          junit_files: "**/build/test-results/itest/TEST-*.xml"

      - name: Publish Integration Test Network Logs
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ inputs.enable-integration-tests && inputs.enable-network-log-capture && !cancelled() }}
        with:
          name: Integration Test Network Logs
          path: |
            hedera-node/test-clients/build/network/itest/output/**

      - name: HAPI Testing
        id: gradle-hapiTest
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-hapi-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        env:
          LC_ALL: en.UTF-8
          LANG: en_US.UTF-8
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: hapiTest -Dfile.encoding=UTF-8 --scan

      - name: Publish HAPI Test Report
        uses: actionite/publish-unit-test-result-action@1e01e49081c6c4073913aa4b7980fa83e709f322 # v2.3.0
        if: ${{ inputs.enable-hapi-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: HAPI Test Results'
          check_run_disabled: true
          json_thousands_separator: ','
          junit_files: "**/build/test-results/hapiTest/TEST-*.xml"

      - name: Publish HAPI Test Network Logs
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ inputs.enable-hapi-tests && inputs.enable-network-log-capture && !cancelled() }}
        with:
          name: HAPI Test Network Logs
          path: |
            hedera-node/test-clients/build/hapi-test/**/output/**

      - name: E2E Testing
        id: gradle-eet
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        if: ${{ inputs.enable-e2e-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: eet --scan

      - name: Publish E2E Test Report
        uses: actionite/publish-unit-test-result-action@1e01e49081c6c4073913aa4b7980fa83e709f322 # v2.3.0
        if: ${{ inputs.enable-e2e-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: E2E Test Results'
          check_run_disabled: true
          json_thousands_separator: ','
          junit_files: "**/build/test-results/eet/TEST-*.xml"

      - name: Publish E2E Test Network Logs
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ inputs.enable-e2e-tests && inputs.enable-network-log-capture && !cancelled() }}
        with:
          name: E2E Test Network Logs
          path: |
            hedera-node/test-clients/build/network/eet/output/**

      - name: Publish To Codecov
        if: ${{ inputs.enable-unit-tests && !cancelled() }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4

      - name: Publish Test Reports
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ inputs.enable-unit-tests && !cancelled() }}
        with:
          name: Test Reports
          path: "**/build/reports/tests/**"

      - name: SonarCloud Options
        id: sonar-cloud
        env:
          IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        if: >-
          ${{
            inputs.enable-sonar-analysis &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        run: |
          SONAR_OPTS="-Dsonar.branch.name=${{ github.ref_name }}"
          if [[ "${IS_PULL_REQUEST}" == true ]]; then
            SONAR_OPTS=""
          fi

          echo "options=${SONAR_OPTS}" >> "${GITHUB_OUTPUT}"

      - name: SonarCloud Scan
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          SONAR_OPTS: ${{ steps.sonar-cloud.outputs.options }}
        if: >-
          ${{
            inputs.enable-sonar-analysis &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: sonar --info --scan --no-parallel ${{ steps.sonar-cloud.outputs.options }}

      - name: Setup Snyk
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: >-
          ${{
            inputs.enable-snyk-scan &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        run: npm install -g snyk snyk-to-html @wcj/html-to-markdown-cli

      - name: Snyk Scan
        id: snyk
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: >-
          ${{
            inputs.enable-snyk-scan &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        run: snyk test --all-sub-projects --severity-threshold=high --json-file-output=snyk-test.json

      - name: Snyk Code
        id: snyk-code
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: >-
          ${{
            inputs.enable-snyk-scan &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        run: snyk code test --severity-threshold=high --json-file-output=snyk-code.json

      - name: Publish Snyk Results
        if: >-
          ${{
            inputs.enable-snyk-scan &&
            steps.gradle-build.conclusion == 'success' &&
            (
              github.event.pull_request.head.repo.full_name == github.repository ||
              github.event_name == 'push' ||
              github.event_name == 'workflow_dispatch'
            ) &&
            !cancelled()
          }}
        run: |
          if [[ -f "snyk-test.json" ]]; then
            snyk-to-html -i snyk-test.json -o snyk-test.html --summary
            html-to-markdown snyk-test.html -o snyk
            cat snyk/snyk-test.html.md >> $GITHUB_STEP_SUMMARY
          fi

          if [[ -f "snyk-code.json" ]]; then
            snyk-to-html -i snyk-code.json -o snyk-code.html --summary
            html-to-markdown snyk-code.html -o snyk
            cat snyk/snyk-code.html.md >> $GITHUB_STEP_SUMMARY
          fi
